"""Noba -- Infrastructure-as-Code export generators.

Generates Ansible playbooks, Docker Compose files, and shell scripts
from live agent data (services, containers, config baselines).
"""
from __future__ import annotations

import logging
import time
from typing import Any

logger = logging.getLogger("noba")


# ── Helpers ──────────────────────────────────────────────────────────────────

def _get_agent_snapshot(
    agent_data: dict[str, dict],
    agent_data_lock: Any,
    agent_max_age: int,
    hostname: str | None = None,
) -> dict[str, dict]:
    """Return a thread-safe snapshot of online agent data.

    If *hostname* is given, only that host is returned (if online).
    """
    now = time.time()
    with agent_data_lock:
        if hostname:
            d = agent_data.get(hostname)
            if d and (now - d.get("_received", 0)) < agent_max_age:
                return {hostname: dict(d)}
            return {}
        return {
            h: dict(d)
            for h, d in agent_data.items()
            if (now - d.get("_received", 0)) < agent_max_age
        }


def _extract_services(data: dict) -> list[dict]:
    """Extract service names from agent data."""
    services = data.get("services", [])
    if isinstance(services, list):
        return services
    return []


def _extract_containers(data: dict) -> list[dict]:
    """Extract container info from agent data."""
    containers = data.get("containers", [])
    if isinstance(containers, list):
        return containers
    return []


def _extract_packages(data: dict) -> list[str]:
    """Extract package list from agent data."""
    pkgs = data.get("packages", [])
    if isinstance(pkgs, list):
        return [str(p) for p in pkgs]
    return []


def _extract_baselines(db: Any, hostname: str | None = None) -> list[dict]:
    """Get drift baselines, optionally filtered to a specific agent group."""
    try:
        baselines = db.list_baselines()
    except Exception:
        return []
    if hostname:
        return [
            b for b in baselines
            if b.get("agent_group") in ("__all__", hostname)
        ]
    return baselines


def _yaml_indent(text: str, indent: int = 0) -> str:
    """Indent every line of *text* by *indent* spaces."""
    prefix = " " * indent
    return "\n".join(prefix + line for line in text.splitlines())


# ── Ansible Playbook Generator ───────────────────────────────────────────────

def generate_ansible(
    db: Any,
    agent_data: dict[str, dict],
    agent_data_lock: Any,
    agent_max_age: int = 120,
    hostname: str | None = None,
) -> str:
    """Generate an Ansible playbook YAML string from agent data.

    If *hostname* is given, the playbook targets only that host.
    Otherwise it produces a play per online agent.
    """
    snapshot = _get_agent_snapshot(agent_data, agent_data_lock, agent_max_age, hostname)
    if not snapshot:
        return "# No online agents found.\n"

    baselines = _extract_baselines(db, hostname)

    lines: list[str] = [
        "---",
        "# Auto-generated by NOBA Command Center",
        f"# Generated: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}",
        "",
    ]

    for host, data in snapshot.items():
        lines.append(f"- name: Configure {host}")
        lines.append(f"  hosts: {host}")
        lines.append("  become: true")
        lines.append("  tasks:")

        has_tasks = False

        # Package installation
        packages = _extract_packages(data)
        if packages:
            has_tasks = True
            lines.append("")
            lines.append(f"    - name: Install packages on {host}")
            lines.append("      ansible.builtin.package:")
            lines.append("        name:")
            for pkg in packages:
                lines.append(f"          - {pkg}")
            lines.append("        state: present")

        # Service enables
        services = _extract_services(data)
        enabled_services = [
            s for s in services
            if isinstance(s, dict) and s.get("state") in ("running", "active")
        ]
        if enabled_services:
            has_tasks = True
            for svc in enabled_services:
                svc_name = svc.get("name", svc.get("unit", "unknown"))
                lines.append("")
                lines.append(f"    - name: Enable and start {svc_name}")
                lines.append("      ansible.builtin.systemd:")
                lines.append(f"        name: {svc_name}")
                lines.append("        state: started")
                lines.append("        enabled: true")

        # Config file templates from baselines
        host_baselines = [
            b for b in baselines
            if b.get("agent_group") in ("__all__", host)
        ]
        if host_baselines:
            has_tasks = True
            for bl in host_baselines:
                path = bl.get("path", "")
                if path:
                    tpl_name = path.lstrip("/").replace("/", "_")
                    lines.append("")
                    lines.append(f"    - name: Deploy config {path}")
                    lines.append("      ansible.builtin.template:")
                    lines.append(f"        src: templates/{tpl_name}.j2")
                    lines.append(f"        dest: {path}")
                    lines.append("        owner: root")
                    lines.append("        group: root")
                    lines.append("        mode: '0644'")

        # Container runs
        containers = _extract_containers(data)
        if containers:
            has_tasks = True
            for ct in containers:
                ct_name = ct.get("name", "unknown")
                ct_image = ct.get("image", "unknown")
                lines.append("")
                lines.append(f"    - name: Run container {ct_name}")
                lines.append("      community.docker.docker_container:")
                lines.append(f"        name: {ct_name}")
                lines.append(f"        image: {ct_image}")
                lines.append("        state: started")
                lines.append("        restart_policy: unless-stopped")
                ports = ct.get("ports", "")
                if ports:
                    lines.append("        ports:")
                    for port_map in str(ports).split(","):
                        port_map = port_map.strip()
                        if port_map:
                            lines.append(f"          - \"{port_map}\"")

        if not has_tasks:
            lines.append("    - name: Placeholder (no data collected)")
            lines.append("      ansible.builtin.debug:")
            lines.append(f"        msg: \"No services/packages/containers discovered on {host}\"")

        lines.append("")

    return "\n".join(lines) + "\n"


# ── Docker Compose Generator ────────────────────────────────────────────────

def generate_docker_compose(
    db: Any,
    agent_data: dict[str, dict],
    agent_data_lock: Any,
    agent_max_age: int = 120,
    hostname: str | None = None,
) -> str:
    """Generate a docker-compose.yml string from container data.

    Requires *hostname* to target a specific agent.
    """
    if not hostname:
        return "# Error: hostname is required for Docker Compose export.\n"

    snapshot = _get_agent_snapshot(agent_data, agent_data_lock, agent_max_age, hostname)
    if not snapshot:
        return f"# No online agent found for hostname: {hostname}\n"

    data = snapshot[hostname]
    containers = _extract_containers(data)

    lines: list[str] = [
        "---",
        "# Auto-generated by NOBA Command Center",
        f"# Host: {hostname}",
        f"# Generated: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}",
        "",
        "services:",
    ]

    if not containers:
        lines.append("  # No containers discovered on this host.")
        return "\n".join(lines) + "\n"

    for ct in containers:
        ct_name = ct.get("name", "unknown")
        ct_image = ct.get("image", "unknown")
        # Sanitize service name for compose (lowercase, no special chars)
        svc_name = ct_name.lower().replace(".", "-").replace("_", "-")

        lines.append(f"  {svc_name}:")
        lines.append(f"    container_name: {ct_name}")
        lines.append(f"    image: {ct_image}")
        lines.append("    restart: unless-stopped")

        ports = ct.get("ports", "")
        if ports:
            port_list = [p.strip() for p in str(ports).split(",") if p.strip()]
            if port_list:
                lines.append("    ports:")
                for p in port_list:
                    lines.append(f"      - \"{p}\"")

        status = ct.get("status", "")
        if "paused" in status.lower():
            lines.append("    # NOTE: container was paused at time of export")

        lines.append("")

    return "\n".join(lines) + "\n"


# ── Shell Script Generator ──────────────────────────────────────────────────

def generate_shell_script(
    db: Any,
    agent_data: dict[str, dict],
    agent_data_lock: Any,
    agent_max_age: int = 120,
    hostname: str | None = None,
) -> str:
    """Generate a bash setup script from agent data.

    Requires *hostname* to target a specific agent.
    """
    if not hostname:
        return "#!/bin/bash\n# Error: hostname is required for shell script export.\nexit 1\n"

    snapshot = _get_agent_snapshot(agent_data, agent_data_lock, agent_max_age, hostname)
    if not snapshot:
        return f"#!/bin/bash\n# No online agent found for hostname: {hostname}\nexit 1\n"

    data = snapshot[hostname]
    packages = _extract_packages(data)
    services = _extract_services(data)
    containers = _extract_containers(data)
    baselines = _extract_baselines(db, hostname)

    lines: list[str] = [
        "#!/bin/bash",
        "# Auto-generated by NOBA Command Center",
        f"# Host: {hostname}",
        f"# Platform: {data.get('platform', 'unknown')}",
        f"# Generated: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}",
        "",
        "set -euo pipefail",
        "",
        'echo "=== NOBA Infrastructure Setup for ' + hostname + ' ==="',
        "",
    ]

    # Package installation section
    lines.append("# ── Package Installation ─────────────────────────────────────────")
    if packages:
        lines.append("echo \"Installing packages...\"")
        lines.append("if command -v apt-get &>/dev/null; then")
        lines.append("    apt-get update -qq")
        pkg_str = " ".join(packages)
        lines.append(f"    apt-get install -y {pkg_str}")
        lines.append("elif command -v dnf &>/dev/null; then")
        lines.append(f"    dnf install -y {pkg_str}")
        lines.append("elif command -v pacman &>/dev/null; then")
        lines.append(f"    pacman -S --noconfirm {pkg_str}")
        lines.append("else")
        lines.append('    echo "WARNING: Unknown package manager, skipping packages"')
        lines.append("fi")
    else:
        lines.append("# No packages discovered.")
    lines.append("")

    # Service enablement section
    lines.append("# ── Service Enablement ───────────────────────────────────────────")
    enabled_services = [
        s for s in services
        if isinstance(s, dict) and s.get("state") in ("running", "active")
    ]
    if enabled_services:
        lines.append("echo \"Enabling services...\"")
        for svc in enabled_services:
            svc_name = svc.get("name", svc.get("unit", "unknown"))
            lines.append(f"systemctl enable --now {svc_name} || true")
    else:
        lines.append("# No active services discovered.")
    lines.append("")

    # Config files section
    lines.append("# ── Config File Baselines ────────────────────────────────────────")
    host_baselines = [
        b for b in baselines
        if b.get("agent_group") in ("__all__", hostname)
    ]
    if host_baselines:
        lines.append("echo \"Checking config baselines...\"")
        for bl in host_baselines:
            path = bl.get("path", "")
            expected = bl.get("expected_hash", "")
            if path:
                lines.append(f"# Baseline: {path} (expected hash: {expected[:16]}...)")
                lines.append(f"if [ -f \"{path}\" ]; then")
                lines.append(f"    echo \"  Config exists: {path}\"")
                lines.append("else")
                lines.append(f"    echo \"  WARNING: Missing config: {path}\"")
                lines.append("fi")
    else:
        lines.append("# No config baselines defined.")
    lines.append("")

    # Container section
    lines.append("# ── Container Deployment ─────────────────────────────────────────")
    if containers:
        lines.append("echo \"Deploying containers...\"")
        lines.append("")
        lines.append("# Detect container runtime")
        lines.append("if command -v docker &>/dev/null; then")
        lines.append("    RUNTIME=docker")
        lines.append("elif command -v podman &>/dev/null; then")
        lines.append("    RUNTIME=podman")
        lines.append("else")
        lines.append('    echo "ERROR: No container runtime found (docker/podman)"')
        lines.append("    exit 1")
        lines.append("fi")
        lines.append("")
        for ct in containers:
            ct_name = ct.get("name", "unknown")
            ct_image = ct.get("image", "unknown")
            ports = ct.get("ports", "")
            lines.append(f"echo \"  Starting container: {ct_name}\"")
            cmd_parts = [
                "$RUNTIME run -d",
                f"--name {ct_name}",
                "--restart unless-stopped",
            ]
            if ports:
                for p in str(ports).split(","):
                    p = p.strip()
                    if p:
                        cmd_parts.append(f"-p {p}")
            cmd_parts.append(ct_image)
            lines.append("  ".join(cmd_parts))
            lines.append("")
    else:
        lines.append("# No containers discovered.")
    lines.append("")

    lines.append('echo "=== Setup complete ==="')
    lines.append("")

    return "\n".join(lines) + "\n"
