"""Tests for Infrastructure-as-Code export generators."""
from __future__ import annotations

import os
import sys
import tempfile
import threading

# Ensure server package is importable
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "share", "noba-web"))

from server.db import Database
from server.iac_export import (
    generate_ansible,
    generate_docker_compose,
    generate_shell_script,
)


def _make_db():
    """Create a fresh temp DB for each test."""
    fd, path = tempfile.mkstemp(suffix=".db", prefix="noba_iactest_")
    os.close(fd)
    return Database(path=path), path


def _cleanup(path):
    for ext in ("", "-wal", "-shm"):
        try:
            os.unlink(path + ext)
        except OSError:
            pass


def _make_agent_store(agents: dict | None = None):
    """Build a fake agent_data dict and lock for tests."""
    import time

    data = {}
    if agents:
        for hostname, extra in agents.items():
            entry = {
                "_received": time.time(),
                "_ip": "10.0.0.1",
                "hostname": hostname,
                "platform": extra.get("platform", "Linux"),
                "arch": extra.get("arch", "x86_64"),
                "agent_version": "2.0.0",
                "cpu_percent": 5.0,
                "mem_percent": 40.0,
            }
            entry.update(extra)
            data[hostname] = entry
    lock = threading.Lock()
    return data, lock


# ── Ansible Generator Tests ─────────────────────────────────────────────────

class TestGenerateAnsible:
    def setup_method(self):
        self.db, self.tmp = _make_db()

    def teardown_method(self):
        _cleanup(self.tmp)

    def test_no_agents_returns_comment(self):
        data, lock = _make_agent_store()
        result = generate_ansible(self.db, data, lock)
        assert result.startswith("# No online agents")

    def test_basic_playbook_structure(self):
        data, lock = _make_agent_store({"web-01": {}})
        result = generate_ansible(self.db, data, lock)
        assert "---" in result
        assert "Auto-generated by NOBA" in result
        assert "- name: Configure web-01" in result
        assert "hosts: web-01" in result
        assert "become: true" in result
        assert "tasks:" in result

    def test_with_packages(self):
        data, lock = _make_agent_store({
            "web-01": {"packages": ["nginx", "curl", "vim"]},
        })
        result = generate_ansible(self.db, data, lock)
        assert "ansible.builtin.package:" in result
        assert "- nginx" in result
        assert "- curl" in result
        assert "- vim" in result
        assert "state: present" in result

    def test_with_services(self):
        data, lock = _make_agent_store({
            "web-01": {
                "services": [
                    {"name": "nginx", "state": "running"},
                    {"name": "sshd", "state": "active"},
                    {"name": "cups", "state": "stopped"},
                ],
            },
        })
        result = generate_ansible(self.db, data, lock)
        assert "Enable and start nginx" in result
        assert "Enable and start sshd" in result
        # stopped service should NOT be enabled
        assert "Enable and start cups" not in result

    def test_with_containers(self):
        data, lock = _make_agent_store({
            "docker-01": {
                "containers": [
                    {"name": "portainer", "image": "portainer/portainer-ce:latest",
                     "status": "Up 2 days", "ports": "8000:8000,9443:9443"},
                ],
            },
        })
        result = generate_ansible(self.db, data, lock)
        assert "Run container portainer" in result
        assert "community.docker.docker_container:" in result
        assert "portainer/portainer-ce:latest" in result

    def test_with_baselines(self):
        self.db.create_baseline("/etc/resolv.conf", "abc123")
        data, lock = _make_agent_store({"web-01": {}})
        result = generate_ansible(self.db, data, lock, hostname="web-01")
        assert "Deploy config /etc/resolv.conf" in result
        assert "ansible.builtin.template:" in result
        assert "etc_resolv.conf.j2" in result

    def test_hostname_filter(self):
        data, lock = _make_agent_store({
            "web-01": {"packages": ["nginx"]},
            "db-01": {"packages": ["postgresql"]},
        })
        result = generate_ansible(self.db, data, lock, hostname="web-01")
        assert "Configure web-01" in result
        assert "Configure db-01" not in result

    def test_multiple_hosts_no_filter(self):
        data, lock = _make_agent_store({
            "web-01": {},
            "db-01": {},
        })
        result = generate_ansible(self.db, data, lock)
        assert "Configure web-01" in result
        assert "Configure db-01" in result


# ── Docker Compose Generator Tests ──────────────────────────────────────────

class TestGenerateDockerCompose:
    def setup_method(self):
        self.db, self.tmp = _make_db()

    def teardown_method(self):
        _cleanup(self.tmp)

    def test_no_hostname_returns_error(self):
        data, lock = _make_agent_store({"web-01": {}})
        result = generate_docker_compose(self.db, data, lock)
        assert "hostname is required" in result

    def test_missing_host_returns_comment(self):
        data, lock = _make_agent_store({})
        result = generate_docker_compose(self.db, data, lock, hostname="missing")
        assert "No online agent" in result

    def test_no_containers_returns_comment(self):
        data, lock = _make_agent_store({"docker-01": {}})
        result = generate_docker_compose(self.db, data, lock, hostname="docker-01")
        assert "services:" in result
        assert "No containers discovered" in result

    def test_basic_compose_structure(self):
        data, lock = _make_agent_store({
            "docker-01": {
                "containers": [
                    {"name": "nginx_proxy", "image": "nginx:alpine",
                     "status": "Up 3 hours", "ports": "80:80,443:443"},
                ],
            },
        })
        result = generate_docker_compose(self.db, data, lock, hostname="docker-01")
        assert "---" in result
        assert "services:" in result
        assert "container_name: nginx_proxy" in result
        assert "image: nginx:alpine" in result
        assert "restart: unless-stopped" in result
        assert '"80:80"' in result
        assert '"443:443"' in result

    def test_multiple_containers(self):
        data, lock = _make_agent_store({
            "docker-01": {
                "containers": [
                    {"name": "app", "image": "myapp:1.0", "status": "Up", "ports": "8080:8080"},
                    {"name": "redis", "image": "redis:7", "status": "Up", "ports": "6379:6379"},
                ],
            },
        })
        result = generate_docker_compose(self.db, data, lock, hostname="docker-01")
        assert "container_name: app" in result
        assert "container_name: redis" in result

    def test_paused_container_gets_note(self):
        data, lock = _make_agent_store({
            "docker-01": {
                "containers": [
                    {"name": "paused_svc", "image": "test:1", "status": "Paused", "ports": ""},
                ],
            },
        })
        result = generate_docker_compose(self.db, data, lock, hostname="docker-01")
        assert "paused at time of export" in result


# ── Shell Script Generator Tests ─────────────────────────────────────────────

class TestGenerateShellScript:
    def setup_method(self):
        self.db, self.tmp = _make_db()

    def teardown_method(self):
        _cleanup(self.tmp)

    def test_no_hostname_returns_error(self):
        data, lock = _make_agent_store({"web-01": {}})
        result = generate_shell_script(self.db, data, lock)
        assert result.startswith("#!/bin/bash")
        assert "hostname is required" in result

    def test_missing_host(self):
        data, lock = _make_agent_store({})
        result = generate_shell_script(self.db, data, lock, hostname="missing")
        assert "No online agent" in result

    def test_basic_script_structure(self):
        data, lock = _make_agent_store({"web-01": {}})
        result = generate_shell_script(self.db, data, lock, hostname="web-01")
        assert result.startswith("#!/bin/bash")
        assert "set -euo pipefail" in result
        assert "NOBA Infrastructure Setup" in result
        assert "Setup complete" in result

    def test_with_packages(self):
        data, lock = _make_agent_store({
            "web-01": {"packages": ["nginx", "curl"]},
        })
        result = generate_shell_script(self.db, data, lock, hostname="web-01")
        assert "Package Installation" in result
        assert "apt-get install -y nginx curl" in result
        assert "dnf install -y nginx curl" in result

    def test_with_services(self):
        data, lock = _make_agent_store({
            "web-01": {
                "services": [
                    {"name": "nginx", "state": "running"},
                    {"name": "mysql", "state": "active"},
                ],
            },
        })
        result = generate_shell_script(self.db, data, lock, hostname="web-01")
        assert "Service Enablement" in result
        assert "systemctl enable --now nginx" in result
        assert "systemctl enable --now mysql" in result

    def test_with_containers(self):
        data, lock = _make_agent_store({
            "docker-01": {
                "containers": [
                    {"name": "portainer", "image": "portainer/portainer-ce:latest",
                     "status": "Up", "ports": "9443:9443"},
                ],
            },
        })
        result = generate_shell_script(self.db, data, lock, hostname="docker-01")
        assert "Container Deployment" in result
        assert "RUNTIME=docker" in result
        assert "portainer/portainer-ce:latest" in result
        assert "-p 9443:9443" in result

    def test_with_baselines(self):
        self.db.create_baseline("/etc/nginx/nginx.conf", "hash123",
                                agent_group="web-01")
        data, lock = _make_agent_store({"web-01": {}})
        result = generate_shell_script(self.db, data, lock, hostname="web-01")
        assert "Config File Baselines" in result
        assert "/etc/nginx/nginx.conf" in result
        assert "hash123" in result[:result.index("hash123") + 20]

    def test_empty_agent_has_all_sections(self):
        """Even with no data, all section headers should appear."""
        data, lock = _make_agent_store({"bare-01": {}})
        result = generate_shell_script(self.db, data, lock, hostname="bare-01")
        assert "Package Installation" in result
        assert "Service Enablement" in result
        assert "Config File Baselines" in result
        assert "Container Deployment" in result
